func recurse(i):
  if i > 100:
    throw("i is too big");
    return;
  end
  recurse(i + 1);
end

func main():
  try:
    recurse(1);
  catch e:
    println(e);
  end

  for i in [0..10]:
    println("hello! " + i);
  end

  try:
    try:
      try:
        function();
      catch e:
        println("Caught exception e: " + e);
        throw("I'm an exception");
      end
    catch f:
      println("here f");
      println("Caught exception f: " + string(f));
      println(null * 5);
    end
  catch g:
    println("here g");
    println("Caught exception g: " + string(g));
  end

  println("here");

  println("you've made it this far solider, thanks to the trusty try/catch");
end
